import { createContext, useContext, useState, useEffect } from 'react';

// ─── Translation dictionary ───────────────────────────────────────────────
const translations = {
  en: {
    // General
    appName: '⚡ KroEasy',
    hello: 'Hello',
    browseServices: 'Browse Services',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading...',
    search: 'Search',
    close: 'Close',
    uploading: 'Uploading...',

    // Tabs
    services: '🔧 Services',
    cars: '🚗 Cars',
    myBookings: '📋 My Bookings',
    profile: '👤 Profile',

    // Services
    noServiceProviders: 'No service providers found',
    tryDifferentFilters: 'Try different filters',
    filterByCity: '🏙️ Filter by city',
    loadMore: 'Load More',

    // Booking
    requestBooking: '📋 Request Booking',
    booking: '⏳ Booking...',
    bookingRequested: '🎉 Booking requested!',
    goToMyBookings: 'Go to My Bookings',
    toCallProvider: 'to call the provider.',
    toCallOwner: 'to call the owner.',
    serviceBooking: '🔧 Service Booking',
    carBooking: '🚗 Car Booking',
    noBookingsYet: 'No bookings yet',
    bookServiceOrCar: 'Book a service or car to get started',
    callProvider: '📞 Call',
    writeReview: '⭐ Write a Review',
    yourReview: '⭐ Your Review',
    pendingBookings: 'Pending Bookings',
    completedBookings: 'Completed Bookings',
    allBookings: 'All Bookings',

    // Profile
    customer: '👤 Customer',
    tapPhotoToView: 'Tap photo to view full size',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    changeLanguage: 'Change Language',
    language: 'Language',
    name: 'Name',
    city: 'City',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updateProfile: 'Update Profile',
    updating: 'Updating...',
    passwordChanged: 'Password changed!',
    profileUpdated: 'Profile updated!',

    // Login
    welcomeBack: 'Welcome Back!',
    loginToAccount: 'Login to access your account',
    phoneNumber: '📱 Phone Number',
    password: '🔒 Password',
    enterPhone: 'Enter your phone number',
    enterPassword: 'Enter your password',
    loginBtn: '🚀 Login',
    loggingIn: '⏳ Logging in...',
    dontHaveAccount: "Don't have an account?",
    registerFree: 'Register Free',
    forgotPassword: 'Forgot Password?',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordInfo: 'Enter your registered phone number. We will create a reset link that admin can send to you.',
    submitRequest: 'Submit Request',
    submitting: 'Submitting...',
    resetRequestSent: 'Reset request submitted! Please contact admin on WhatsApp/phone to get your reset link.',
    backToLogin: '← Back to Login',

    // Drawers
    serviceProviderProfile: 'Service Provider Profile',
    carDetails: 'Car Details',
    availableNow: '✅ Available Now',
    currentlyBusy: '⏸️ Currently Busy',
    skills: '🔧 Skills',
    details: 'ℹ️ Details',
    experience: '💼 Experience',
    years: 'years',
    charges: '💰 Charges',
    customerReviews: '⭐ Customer Reviews',
    noReviewsYet: 'No reviews yet — be the first!',
    showMore: 'Show More',
    remaining: 'remaining',
    rating: 'Rating',
    bookingsDone: 'Bookings Done',
    bookingsCompleted: 'Bookings Completed',
    callOwner: '📞 Call Owner Directly',

    // Success page
    requestSent: 'Request Sent!',
    successMsg1: 'Your booking request has been sent successfully.',
    successMsg2: 'The worker will contact you shortly.',
    checkStatusIn: 'Check status in',
    myBookingSection: 'My Bookings',
    section: 'section.',
    goToBookings: 'Go to My Bookings',
    goHome: 'Go to Home',

    // Landing page
    share: 'Share',
    dashboard: 'Dashboard',
    landingTagline: 'Apna Kaam, Easy Kaam',
    heroH1a: '🏠 Need home work done?',
    heroH1b: 'Find in One Tap!',
    heroSubHi: 'Book a Car?',
    heroSubServices: 'Electrician • Plumber • AC Repair • Beautician',
    heroSubLine2: 'All verified — No middleman, completely Free!',
    heroCta1: '🔧 Find Worker — Free!',
    heroCta2: '🚗 Book a Car',
    heroInstallIos: '📲 Install App (iPhone)',
    heroInstallAndroid: '📲 Install App — Free!',
    iosHintText: '📱 In Safari tap Share ⬆ then select "Add to Home Screen"',
    heroTrust: 'verified workers near you',
    statUsers: 'Happy Customers',
    statJobs: 'Jobs Done',
    statWorkers: 'Workers',
    whyTitle: 'Who is this App for?',
    whySub: '3 types of people use KroEasy',
    for_customer_title: 'Customers',
    for_customer_desc: 'Get home work done — Electrician, AC, Plumber, Beautician — verified workers, no middleman!',
    for_customer_btn: 'Find Now →',
    for_worker_title: 'Workers / Labourers',
    for_worker_desc: 'Show your work online. Get direct calls from customers. Zero commission!',
    for_worker_btn: 'Register →',
    for_car_title: 'Car Owners',
    for_car_desc: 'List your car for rent. Build a profile and get bookings in your city.',
    for_car_btn: 'Register →',
    pickService: 'Choose Your Service',
    pickServiceSub: 'Tap — worker list opens instantly',
    howItWorksTitle: 'How does it work?',
    step1Title: 'Choose Service', step1Desc: 'Tap a category or search by city',
    step2Title: 'Book', step2Desc: 'Send booking request in one tap — completely FREE!',
    step3Title: 'Call & Get Work Done', step3Desc: 'Call worker directly, agree on price, work done!',
    testimonialsTitle: 'What are people saying?',
    beforeAfterTitle: '😩 Old Way vs ⚡ Now',
    compareOld1: '❌ Ask someone, wait', compareNew1: '✅ Browse instantly',
    compareOld2: '❌ Pay middleman fee', compareNew2: '✅ Direct contact, FREE',
    compareOld3: '❌ No quality guarantee', compareNew3: '✅ Ratings & reviews visible',
    compareOld4: '❌ Had to remember numbers', compareNew4: '✅ All in one place — App',
    workerCtaTitle: 'Are you a worker? Register here!',
    workerCtaDesc: 'Build a free profile. Customers will call you directly. No commission — all money is yours.',
    workerCtaBtn: '🔧 Worker Register',
    carOwnerCtaBtn: '🚗 Car Owner',
    finalCtaTitle: 'Try today — Free!',
    finalCtaDesc: 'No registration needed to browse. See and get work done!',
    browseServices: '⚡ See Services — Now!',
    registerFree: '✨ Free Register',
    installBannerTitle: 'Install KroEasy App — Free!',
    installBannerSub: 'Works offline • Home screen icon',
    trust1Title: 'Admin Verified', trust1Desc: 'Every worker checked by our team',
    trust2Title: 'Rating System', trust2Desc: 'Give reviews after booking',
    trust3Title: 'Direct Call', trust3Desc: 'No middleman — call directly',
    trust4Title: 'Safe Platform', trust4Desc: 'Your number is secure with us',
    footerServices: 'Services',
    footerSupport: 'Support',
    footerFindWorker: '🔧 Find Workers',
    footerBookCar: '🚗 Book a Car',
    footerRegister: '👤 Free Register',
    footerHelp: '🛠️ Help',
    footerTerms: '📜 Terms',
    footerPrivacy: '🔒 Privacy',
    footerContact: 'Contact',
    footerCopyright: '© 2025 KroEasy. Made with ❤️ for small-town India.',
    linkCopied: '🔗 Link copied!',
    // Other skill filter
    skillOther: 'Other',
    skillOtherFilter: '🎯 Other Skills',
    skillElectrician: 'Electrician',
    skillPlumber: 'Plumber',
    skillCarpenter: 'Carpenter',
    skillWelder: 'Welder',
    skillAcRepair: 'AC Technician',
    skillMason: 'Mason',
    skillBeautician: 'Beautician',
    skillMehndi: 'Mehndi Artist',
    skillHelper: 'Helper',

    // Car owner dashboard
    carOwnerDashboard: '🚗 Car Owner Dashboard',
    myCars: '🚗 My Cars',
    totalCars: 'Total Cars',
    totalLeads: 'Total Leads',
    addNewCar: '➕ Add New Car',
    editCar: '✏️ Edit Car',
    saveCar: '💾 Save Car',
    deleteCar: '🗑️ Delete',
    carName: 'Car Name',
    numberPlate: 'Number Plate',
    modelYear: 'Model Year',
    basePrice: 'Base Price (₹)',
    priceType: 'Price Type',
    perDay: 'Per Day',
    perKm: 'Per KM',
    acLabel: '❄️ AC',
    driverIncluded: '🧑‍✈️ Driver Included',
    noBookingsYetProvider: 'No bookings yet',
    markCompleted: '🎉 Mark as Completed',
    approvalPending: 'Approval Pending',
    accountApproved: 'Account Approved!',
    accountRejected: 'Account Rejected',
    accountSuspended: 'Account Suspended',
    carOwnerBadge: '🚗 Car Owner',
    workerBadge: '🔧 Service Provider',
    enterNewPassword: 'Enter New Password',
    confirmPassword: 'Confirm Password',
    passwordsNotMatch: 'Passwords do not match',
    resetSuccess: 'Password reset successful! You can now login.',
    resetBtn: '🔓 Reset Password',

    // Landing — compare section
    compareTitle: '😩 Old Way vs ⚡ KroEasy',
    compareSub: 'See the difference',
    compareOld1: '❌ Kisi se pucho, wait karo',
    compareNew1: '✅ Instantly browse providers',
    compareOld2: '❌ No guarantee of quality',
    compareNew2: '✅ Verified & rated profiles',
    compareOld3: '❌ Hidden charges, dalaal fees',
    compareNew3: '✅ Direct contact, no middleman',
    compareOld4: '❌ No history or record',
    compareNew4: '✅ Booking history + call logs',

    // Landing — footer
    footerFeatures: 'Features',
    footerSupportLegal: 'Support & Legal',
    footerContact: 'Contact',
    footerServiceProviders: '🔧 Service Providers',
    footerCarBooking: '🚗 Car Booking',
    footerRegisterFree: '👤 Register Free',
    footerLoginLink: '🔒 Login',
    footerHelp: '🛠️ Help & Support',
    footerTerms: '📜 Terms & Conditions',
    footerPrivacy: '🔒 Privacy Policy',
    footerCopyright: '© 2025 KroEasy. Made with ❤️ for small-town India.',
    footerRegion: 'Nowrozabad & Birshingpur Pali, MP',
    linkCopied: '🔗 Link copied!',

    // Register page
    registerTitle: 'Create Account',
    registerSub: 'Join KroEasy for free',
    iAmA: 'I am a...',
    roleCustomerLabel: '👤 Customer',
    roleCustomerDesc: 'Hire services or book cars',
    roleWorkerLabel: '🔧 Service Provider',
    roleWorkerDesc: 'Offer your skills & get hired',
    roleCarOwnerLabel: '🚗 Car Owner',
    roleCarOwnerDesc: 'List your car for booking',
    fullName: 'Full Name *',
    fullNamePlaceholder: 'Your full name',
    phoneNumberReq: 'Phone Number *',
    phonePlaceholder: '10-digit phone number',
    passwordReq: 'Password *',
    passwordPlaceholder: 'Min 6 characters',
    cityReq: 'City *',
    cityPlaceholder: 'Your city',
    skillsLabel: 'Skills * (select all that apply)',
    otherCustom: '🎯 Other (custom)',
    customSkillPlaceholder: 'Type your skill (e.g. Tailor, Welder, Barber...)',
    customSkillAdded: '✅ Will be added:',
    experienceYears: 'Experience (years)',
    aboutYourself: 'About Yourself',
    descPlaceholder: 'Describe your experience...',
    creatingAccount: '⏳ Creating Account...',
    createAccountFree: '🎉 Create Account Free',
    byClickingCreate: 'By clicking',
    createAccountText: 'Create Account',
    youAgree: ', you agree to our',
    andText: 'and',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    alreadyAccount: 'Already have an account?',
    loginLink: 'Login',
    errorFillAll: 'कृपया सभी जरूरी फील्ड भरें (नाम, फ़ोन, पासवर्ड, शहर)।',
    errorPassword6: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए।',
    errorSelectSkill: 'कृपया कम से कम एक कौशल चुनें।',

    // Labour dashboard
    labourDashTitle: '🔧 Service Provider Dashboard',
    tabDashboard: '📊 Dashboard',
    tabProfile: '👤 Profile',
    tabBookings: '📋 Bookings',
    totalBookings: 'Total Bookings',
    totalLeads: 'Total Leads',
    reviews: 'Reviews',
    availability: 'Availability',
    availableNowText: '✅ Currently Available',
    notAvailable: '⏸️ Not Available',
    profileSummary: 'Profile Summary',
    chargesLabel: 'Charges',
    notSet: 'Not set',
    editProfileBtn: '✏️ Edit Profile',
    editProfileTitle: 'Edit Profile',
    skillsField: 'Skills',
    experienceYrs: 'Experience (yrs)',
    chargesField: 'Charges',
    descField: 'Description',
    saveBtn: '💾 Save',
    pendingApprovalTitle: 'Pending Approval',
    pendingApprovalText: "Your profile is under review. You'll be visible after admin approval.",
    approvedTitle: 'Account Approved!',
    approvedText: 'Congratulations! Your profile is live and customers can find and book you.',
    rejectedTitle: 'Account Rejected',
    rejectedText: 'Your account was rejected by admin. Please contact support for more information.',
    noBookingsText: 'No bookings yet',
    confirmBtn: '✅ Confirm',
    cancelBtnLabel: '❌ Cancel',
    markCompletedBtn: '🎉 Mark as Completed',
    customerReviewLabel: '⭐ Customer Review',

    // Status labels
    statusPending: '⏳ Pending',
    statusConfirmed: '✅ Confirmed',
    statusCompleted: '🎉 Completed',
    statusCancelled: '❌ Cancelled',
    filterAll: '📋 All',
    noCarsAvailable: 'No cars available',
    cancelBookingConfirm: 'Cancel this booking request?',
    ownerLabel: 'Owner',
    dayLabel: 'day',
    kmLabel: 'km',

    // Review modal
    writeReviewTitle: 'Write a Review ⭐',
    reviewWorkerExp: 'How was your experience with this worker?',
    reviewCarExp: 'How was your experience with this car service?',
    ratingPoor: 'Poor', ratingFair: 'Fair', ratingGood: 'Good',
    ratingVeryGood: 'Very Good', ratingExcellent: 'Excellent!',
    rateTap: 'Tap to rate',
    reviewPlaceholder: 'Share your experience (optional)...',
    submitReview: '✅ Submit Review',
    submittingReview: '⏳ Submitting...',
    loginFailed: 'Login Failed',
    locationLabel: 'Nowrozabad & Birshingpur Pali',

    // Car Owner Dashboard
    carOwnerDashboard: '🚗 Car Owner Dashboard',
    myCars: '🚗 My Cars',
    totalCars: 'Total Cars',
    myBookings: 'Bookings',
    carName: 'Car Name',
    numberPlate: 'Number Plate',
    modelYear: 'Model Year',
    basePrice: 'Price per km (₹) *',
    saveCar: '💾 Save Car',
    addNewCar: '➕ Add New Car',
    editCar: '✏️ Edit',
    deleteCar: '🗑️ Delete',
    carOwnerBadge: '🚗 Car Owner',
    tapPhotoToView: 'Tap photo to view full size',
    accountSuspended: 'Account Suspended',
  },

  hi: {
    // General
    appName: '⚡ KroEasy',
    hello: 'नमस्ते',
    browseServices: 'सेवाएं देखें',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    loading: 'लोड हो रहा है...',
    search: 'खोजें',
    close: 'बंद करें',

    // Tabs
    services: '🔧 सेवाएं',
    cars: '🚗 कारें',
    myBookings: '📋 मेरी बुकिंग',
    profile: '👤 प्रोफ़ाइल',

    // Services
    noServiceProviders: 'कोई सेवा प्रदाता नहीं मिला',
    tryDifferentFilters: 'अलग फ़िल्टर आज़माएं',
    filterByCity: '🏙️ शहर से खोजें',
    loadMore: 'और लोड करें',

    // Booking
    requestBooking: '📋 बुकिंग अनुरोध करें',
    booking: '⏳ बुकिंग हो रही है...',
    bookingRequested: '🎉 बुकिंग अनुरोध भेजा गया!',
    goToMyBookings: 'मेरी बुकिंग पर जाएं',
    toCallProvider: 'सेवा प्रदाता को कॉल करने के लिए।',
    toCallOwner: 'मालिक को कॉल करने के लिए।',
    serviceBooking: '🔧 सेवा बुकिंग',
    carBooking: '🚗 कार बुकिंग',
    noBookingsYet: 'अभी कोई बुकिंग नहीं',
    bookServiceOrCar: 'शुरू करने के लिए कोई सेवा या कार बुक करें',
    callProvider: '📞 कॉल करें',
    writeReview: '⭐ समीक्षा लिखें',
    yourReview: '⭐ आपकी समीक्षा',
    pendingBookings: 'प्रतीक्षारत बुकिंग',
    completedBookings: 'पूर्ण बुकिंग',
    allBookings: 'सभी बुकिंग',

    // Profile
    customer: '👤 ग्राहक',
    tapPhotoToView: 'पूरा आकार देखने के लिए फोटो टैप करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    changePassword: 'पासवर्ड बदलें',
    changeLanguage: 'भाषा बदलें',
    language: 'भाषा',
    name: 'नाम',
    city: 'शहर',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmNewPassword: 'नया पासवर्ड दोबारा डालें',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    updating: 'अपडेट हो रहा है...',
    passwordChanged: 'पासवर्ड बदल गया!',
    profileUpdated: 'प्रोफ़ाइल अपडेट हो गई!',

    // Login
    welcomeBack: 'वापस स्वागत है!',
    loginToAccount: 'अपने खाते तक पहुँचने के लिए लॉगिन करें',
    phoneNumber: '📱 फ़ोन नंबर',
    password: '🔒 पासवर्ड',
    enterPhone: 'अपना फ़ोन नंबर दर्ज करें',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    loginBtn: '🚀 लॉगिन',
    loggingIn: '⏳ लॉगिन हो रहा है...',
    dontHaveAccount: 'खाता नहीं है?',
    registerFree: 'मुफ़्त रजिस्टर करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    forgotPasswordTitle: 'पासवर्ड भूल गए',
    forgotPasswordInfo: 'अपना पंजीकृत फ़ोन नंबर दर्ज करें। हम एक रीसेट लिंक बनाएंगे जिसे एडमिन आपको भेज सकते हैं।',
    submitRequest: 'अनुरोध भेजें',
    submitting: 'भेजा जा रहा है...',
    resetRequestSent: 'रीसेट अनुरोध भेजा गया! रीसेट लिंक पाने के लिए Admin से WhatsApp/फोन पर संपर्क करें।',
    backToLogin: '← वापस लॉगिन पर',

    // Drawers
    serviceProviderProfile: 'सेवा प्रदाता प्रोफ़ाइल',
    carDetails: 'कार विवरण',
    availableNow: '✅ अभी उपलब्ध',
    currentlyBusy: '⏸️ अभी व्यस्त',
    skills: '🔧 कौशल',
    details: 'ℹ️ विवरण',
    experience: '💼 अनुभव',
    years: 'वर्ष',
    charges: '💰 शुल्क',
    customerReviews: '⭐ ग्राहक समीक्षाएं',
    noReviewsYet: 'अभी कोई समीक्षा नहीं — पहले बनें!',
    showMore: 'और दिखाएं',
    remaining: 'बाकी',
    rating: 'रेटिंग',
    bookingsDone: 'पूर्ण बुकिंग',
    bookingsCompleted: 'बुकिंग पूरी',
    callOwner: '📞 मालिक को सीधे कॉल करें',

    // Success page
    requestSent: 'अनुरोध भेजा गया!',
    successMsg1: 'आपका बुकिंग अनुरोध सफलतापूर्वक भेज दिया गया है।',
    successMsg2: 'कार्यकर्ता जल्द ही आपसे संपर्क करेगा।',
    checkStatusIn: 'स्थिति देखें',
    myBookingSection: 'मेरी बुकिंग',
    section: 'में।',
    goToBookings: 'मेरी बुकिंग देखें',
    goHome: 'होम पर जाएं',

    // Landing page
    share: 'शेयर करें',
    dashboard: 'डैशबोर्ड',
    landingTagline: 'अपना काम, आसान काम',
    heroH1a: '🏠 घर का काम चाहिए?',
    heroH1b: 'एक टैप में मिलेगा!',
    heroSubHi: 'गाड़ी बुक करनी है?',
    heroSubServices: 'बिजली मिस्त्री • प्लंबर • AC Repair • ब्यूटीशियन',
    heroSubLine2: 'सभी verified — कोई दलाल नहीं, बिल्कुल मुफ़्त!',
    heroCta1: '🔧 कामगार खोजें — Free!',
    heroCta2: '🚗 गाड़ी बुक करें',
    heroInstallIos: '📲 App Install करें (iPhone)',
    heroInstallAndroid: '📲 App Install करें — मुफ़्त!',
    iosHintText: '📱 Safari में Share ⬆ दबाएं → "Add to Home Screen" चुनें',
    heroTrust: 'verified कामगार आपके पास',
    statUsers: 'खुश ग्राहक',
    statJobs: 'काम पूरे',
    statWorkers: 'कामगार',
    whyTitle: 'यह App किसके लिए है?',
    whySub: '3 तरह के लोग KroEasy पर हैं',
    for_customer_title: 'घर वाले',
    for_customer_desc: 'घर का काम करवाएं — बिजली, पानी, AC, ब्यूटीशियन — verified कामगार से, बिना दलाल!',
    for_customer_btn: 'अभी देखें →',
    for_worker_title: 'कामगार / मजदूर',
    for_worker_desc: 'अपना काम online दिखाएं। सीधे customers से call आएगी। कोई commission नहीं!',
    for_worker_btn: 'Register करें →',
    for_car_title: 'गाड़ी मालिक',
    for_car_desc: 'अपनी गाड़ी rent पर दें। Profile बनाएं और शहर में booking पाएं।',
    for_car_btn: 'Register करें →',
    pickService: 'अपनी सेवा चुनें',
    pickServiceSub: 'टैप करें — कामगारों की लिस्ट खुलेगी',
    howItWorksTitle: 'कैसे काम करता है?',
    step1Title: 'सेवा चुनें', step1Desc: 'Category tap करें या शहर से search करें',
    step2Title: 'Booking करें', step2Desc: 'एक tap में booking request — बिल्कुल FREE!',
    step3Title: 'Call करें', step3Desc: 'कामगार से directly call करें, दाम तय करें, काम हो!',
    testimonialsTitle: 'लोग क्या कह रहे हैं?',
    beforeAfterTitle: '😩 पहले vs ⚡ अब',
    compareOld1: '❌ किसी से पूछो, इंतज़ार करो', compareNew1: '✅ तुरंत देखें',
    compareOld2: '❌ दलाल को पैसे दो', compareNew2: '✅ Direct contact, FREE',
    compareOld3: '❌ Quality की guarantee नहीं', compareNew3: '✅ Rating & reviews दिखते हैं',
    compareOld4: '❌ नंबर याद करना पड़ता था', compareNew4: '✅ सब एक जगह — App में',
    workerCtaTitle: 'कामगार हो? यहाँ Register करो!',
    workerCtaDesc: 'मुफ़्त profile बनाएं। Customers सीधे call करेंगे। कोई commission नहीं।',
    workerCtaBtn: '🔧 Worker Register',
    carOwnerCtaBtn: '🚗 Car Owner',
    finalCtaTitle: 'आज ही try करो — Free!',
    finalCtaDesc: 'Browse करने के लिए register भी नहीं चाहिए। देखो और काम करवाओ!',
    browseServices: '⚡ सेवाएं देखें — अभी!',
    registerFree: '✨ Free Register',
    installBannerTitle: 'KroEasy App Install करें — Free!',
    installBannerSub: 'Offline भी चलेगा • Home screen पर icon',
    trust1Title: 'Admin Verified', trust1Desc: 'हर कामगार को admin check करता है',
    trust2Title: 'Rating System', trust2Desc: 'Booking के बाद review दें',
    trust3Title: 'Direct Call', trust3Desc: 'बिना बिचौलिए, सीधे call करें',
    trust4Title: 'Safe Platform', trust4Desc: 'आपका नंबर सुरक्षित है',
    footerServices: 'सेवाएं',
    footerSupport: 'सहायता',
    footerFindWorker: '🔧 कामगार खोजें',
    footerBookCar: '🚗 गाड़ी बुक करें',
    footerRegister: '👤 Free Register',
    footerHelp: '🛠️ सहायता',
    footerTerms: '📜 नियम',
    footerPrivacy: '🔒 Privacy',
    footerContact: 'संपर्क',
    footerCopyright: '© 2025 KroEasy. ❤️ के साथ बनाया छोटे शहरों के लिए।',
    linkCopied: '🔗 लिंक कॉपी हो गया!',
    // Other skill filter
    skillOther: 'अन्य',
    skillOtherFilter: '🎯 अन्य कौशल',
    skillElectrician: 'बिजली मिस्त्री',
    skillPlumber: 'प्लंबर',
    skillCarpenter: 'बढ़ई',
    skillWelder: 'वेल्डर',
    skillAcRepair: 'AC तकनीशियन',
    skillMason: 'राजमिस्त्री',
    skillBeautician: 'ब्यूटीशियन',
    skillMehndi: 'मेहंदी कलाकार',
    skillHelper: 'सहायक',
    skillMehndi: 'मेहंदी कलाकार',
    skillHelper: 'सहायक',

    // Car owner dashboard
    carOwnerDashboard: '🚗 कार मालिक डैशबोर्ड',
    myCars: '🚗 मेरी कारें',
    totalCars: 'कुल कारें',
    totalLeads: 'कुल लीड्स',
    addNewCar: '➕ नई कार जोड़ें',
    editCar: '✏️ कार संपादित करें',
    saveCar: '💾 कार सेव करें',
    deleteCar: '🗑️ हटाएं',
    carName: 'कार का नाम',
    numberPlate: 'नंबर प्लेट',
    modelYear: 'मॉडल वर्ष',
    basePrice: 'मूल कीमत (₹)',
    priceType: 'मूल्य प्रकार',
    perDay: 'प्रति दिन',
    perKm: 'प्रति किमी',
    acLabel: '❄️ AC',
    driverIncluded: '🧑‍✈️ ड्राइवर सहित',
    noBookingsYetProvider: 'अभी कोई बुकिंग नहीं',
    markCompleted: '🎉 पूर्ण के रूप में चिह्नित करें',
    approvalPending: 'अनुमोदन प्रतीक्षारत',
    accountApproved: 'खाता अनुमोदित!',
    accountRejected: 'खाता अस्वीकृत',
    accountSuspended: 'खाता निलंबित',
    carOwnerBadge: '🚗 कार मालिक',
    workerBadge: '🔧 सेवा प्रदाता',
    enterNewPassword: 'नया पासवर्ड डालें',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    passwordsNotMatch: 'पासवर्ड मेल नहीं खाते',
    resetSuccess: 'पासवर्ड रीसेट सफल! अब आप लॉगिन कर सकते हैं।',
    resetBtn: '🔓 पासवर्ड रीसेट करें',

    // Landing — compare section
    compareTitle: '😩 पुराना तरीका vs ⚡ KroEasy',
    compareSub: 'फर्क देखें',
    compareOld1: '❌ किसी से पूछो, इंतजार करो',
    compareNew1: '✅ तुरंत प्रदाता ब्राउज़ करें',
    compareOld2: '❌ गुणवत्ता की कोई गारंटी नहीं',
    compareNew2: '✅ सत्यापित और रेटेड प्रोफ़ाइल',
    compareOld3: '❌ छिपे शुल्क, दलाल की फीस',
    compareNew3: '✅ सीधा संपर्क, कोई बिचौलिया नहीं',
    compareOld4: '❌ कोई इतिहास या रिकॉर्ड नहीं',
    compareNew4: '✅ बुकिंग इतिहास + कॉल लॉग',

    // Landing — footer
    footerFeatures: 'सुविधाएं',
    footerSupportLegal: 'सहायता और कानूनी',
    footerContact: 'संपर्क',
    footerServiceProviders: '🔧 सेवा प्रदाता',
    footerCarBooking: '🚗 कार बुकिंग',
    footerRegisterFree: '👤 मुफ़्त रजिस्टर करें',
    footerLoginLink: '🔒 लॉगिन',
    footerHelp: '🛠️ सहायता',
    footerTerms: '📜 नियम और शर्तें',
    footerPrivacy: '🔒 गोपनीयता नीति',
    footerCopyright: '© 2025 KroEasy. ❤️ के साथ बनाया छोटे शहरों के लिए।',
    footerRegion: 'नौरोजाबाद एवं बिरसिंहपुर पाली, MP',
    linkCopied: '🔗 लिंक कॉपी हो गया!',

    // Register page
    registerTitle: 'खाता बनाएं',
    registerSub: 'KroEasy पर मुफ़्त जुड़ें',
    iAmA: 'मैं हूँ...',
    roleCustomerLabel: '👤 ग्राहक',
    roleCustomerDesc: 'सेवाएं लें या कार बुक करें',
    roleWorkerLabel: '🔧 सेवा प्रदाता',
    roleWorkerDesc: 'अपनी कौशल दें और काम पाएं',
    roleCarOwnerLabel: '🚗 कार मालिक',
    roleCarOwnerDesc: 'अपनी कार बुकिंग के लिए लिस्ट करें',
    fullName: 'पूरा नाम *',
    fullNamePlaceholder: 'आपका पूरा नाम',
    phoneNumberReq: 'फ़ोन नंबर *',
    phonePlaceholder: '10 अंकों का फ़ोन नंबर',
    passwordReq: 'पासवर्ड *',
    passwordPlaceholder: 'कम से कम 6 अक्षर',
    cityReq: 'शहर *',
    cityPlaceholder: 'आपका शहर',
    skillsLabel: 'कौशल * (सभी लागू चुनें)',
    otherCustom: '🎯 अन्य (कस्टम)',
    customSkillPlaceholder: 'अपना कौशल टाइप करें (जैसे दर्जी, वेल्डर, नाई...)',
    customSkillAdded: '✅ जोड़ा जाएगा:',
    experienceYears: 'अनुभव (वर्ष)',
    aboutYourself: 'अपने बारे में',
    descPlaceholder: 'अपना अनुभव बताएं...',
    creatingAccount: '⏳ खाता बन रहा है...',
    createAccountFree: '🎉 मुफ़्त खाता बनाएं',
    byClickingCreate: '',
    createAccountText: 'खाता बनाएं',
    youAgree: 'पर क्लिक करके आप हमारी',
    andText: 'और',
    termsConditions: 'नियम और शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    alreadyAccount: 'पहले से खाता है?',
    loginLink: 'लॉगिन करें',
    errorFillAll: 'कृपया सभी जरूरी फील्ड भरें (नाम, फ़ोन, पासवर्ड, शहर)।',
    errorPassword6: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए।',
    errorSelectSkill: 'कृपया कम से कम एक कौशल चुनें।',

    // Labour dashboard
    labourDashTitle: '🔧 सेवा प्रदाता डैशबोर्ड',
    tabDashboard: '📊 डैशबोर्ड',
    tabProfile: '👤 प्रोफ़ाइल',
    tabBookings: '📋 बुकिंग',
    totalBookings: 'कुल बुकिंग',
    totalLeads: 'कुल लीड्स',
    reviews: 'समीक्षाएं',
    availability: 'उपलब्धता',
    availableNowText: '✅ अभी उपलब्ध',
    notAvailable: '⏸️ उपलब्ध नहीं',
    profileSummary: 'प्रोफ़ाइल सारांश',
    chargesLabel: 'शुल्क',
    notSet: 'सेट नहीं',
    editProfileBtn: '✏️ प्रोफ़ाइल संपादित करें',
    editProfileTitle: 'प्रोफ़ाइल संपादित करें',
    skillsField: 'कौशल',
    experienceYrs: 'अनुभव (वर्ष)',
    chargesField: 'शुल्क',
    descField: 'विवरण',
    saveBtn: '💾 सेव करें',
    pendingApprovalTitle: 'अनुमोदन प्रतीक्षारत',
    pendingApprovalText: 'आपकी प्रोफ़ाइल समीक्षाधीन है। Admin के अनुमोदन के बाद दिखेगी।',
    approvedTitle: 'खाता अनुमोदित!',
    approvedText: 'बधाई! आपकी प्रोफ़ाइल लाइव है और ग्राहक आपको ढूंढ सकते हैं।',
    rejectedTitle: 'खाता अस्वीकृत',
    rejectedText: 'आपका खाता admin ने अस्वीकार कर दिया। अधिक जानकारी के लिए सहायता से संपर्क करें।',
    noBookingsText: 'अभी कोई बुकिंग नहीं',
    confirmBtn: '✅ स्वीकार करें',
    cancelBtnLabel: '❌ रद्द करें',
    markCompletedBtn: '🎉 पूर्ण के रूप में चिह्नित करें',
    customerReviewLabel: '⭐ ग्राहक समीक्षा',

    // Status labels
    statusPending: '⏳ प्रतीक्षारत',
    statusConfirmed: '✅ स्वीकृत',
    statusCompleted: '🎉 पूर्ण',
    statusCancelled: '❌ रद्द',
    filterAll: '📋 सभी',
    noCarsAvailable: 'कोई कार उपलब्ध नहीं',
    cancelBookingConfirm: 'इस बुकिंग को रद्द करें?',
    ownerLabel: 'मालिक',
    dayLabel: 'दिन',
    kmLabel: 'किमी',

    // Review modal
    writeReviewTitle: 'समीक्षा लिखें ⭐',
    reviewWorkerExp: 'इस कर्मी के साथ आपका अनुभव कैसा रहा?',
    reviewCarExp: 'इस कार सेवा के साथ आपका अनुभव कैसा रहा?',
    ratingPoor: 'खराब', ratingFair: 'ठीक', ratingGood: 'अच्छा',
    ratingVeryGood: 'बहुत अच्छा', ratingExcellent: 'बेहतरीन!',
    rateTap: 'रेट करने के लिए टैप करें',
    reviewPlaceholder: 'अपना अनुभव साझा करें (वैकल्पिक)...',
    submitReview: '✅ समीक्षा सबमिट करें',
    submittingReview: '⏳ सबमिट हो रहा है...',
    loginFailed: 'लॉगिन विफल',
    locationLabel: 'नौरोजाबाद एवं बिरसिंहपुर पाली',

    // Extra keys for new pages
    tapPhotoToView: 'पूरा देखने के लिए फ़ोटो टैप करें',
    myBookings: 'बुकिंग',
    basePrice: 'कीमत प्रति किमी (₹) *',
  },
};

// ─── Context ─────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('kroeasy_lang') || 'hi');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('kroeasy_lang', l);
  };

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  useEffect(() => {
    document.documentElement.lang = lang === 'hi' ? 'hi' : 'en';
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
